#!/usr/bin/env python3
"""
Usage: python3 apply.py <plan.json> <root_folder> [--dry-run]

Applies a music sort plan and writes undo.sh to <root_folder>.

Plan format — a JSON array of objects, each with an "action" field:
  {"action": "MOVE",   "src": "/abs/src.mp3", "dst": "/abs/dst.mp3"}
  {"action": "DELETE", "src": "/abs/dup.mp3"}
  {"action": "SKIP",   "src": "/abs/file.mp3", "reason": "..."}

Exits non-zero on the first error. Prints a summary to stdout.
"""

import json
import os
import shutil
import sys


def main():
    if len(sys.argv) < 3:
        print('Usage: apply.py <plan.json> <root_folder> [--dry-run]', file=sys.stderr)
        sys.exit(1)

    plan_path   = sys.argv[1]
    root_folder = os.path.expanduser(sys.argv[2])
    dry_run     = '--dry-run' in sys.argv

    with open(plan_path) as f:
        plan = json.load(f)

    moves   = [p for p in plan if p['action'] == 'MOVE']
    deletes = [p for p in plan if p['action'] == 'DELETE']
    skips   = [p for p in plan if p['action'] == 'SKIP']

    if dry_run:
        print(f'[dry-run] Would move {len(moves)} file(s), delete {len(deletes)}, skip {len(skips)}.')
        return

    undo_lines = ['#!/usr/bin/env bash', '# Undo script generated by music-sort', '']
    moved = deleted = errors = 0
    created_dirs = set()

    for entry in moves:
        src, dst = entry['src'], entry['dst']
        try:
            dst_dir = os.path.dirname(dst)
            # Track newly created directories so undo.sh can remove them
            parts = []
            d = dst_dir
            while not os.path.exists(d):
                parts.append(d)
                d = os.path.dirname(d)
            created_dirs.update(parts)
            os.makedirs(dst_dir, exist_ok=True)
            shutil.move(src, dst)
            undo_lines.append(f'mv {json.dumps(dst)} {json.dumps(src)}')
            moved += 1
        except Exception as e:
            print(f'ERROR moving {src} → {dst}: {e}', file=sys.stderr)
            errors += 1

    for entry in deletes:
        src = entry['src']
        try:
            undo_lines.append(f'# DELETED (cannot undo automatically): {src}')
            os.remove(src)
            deleted += 1
        except Exception as e:
            print(f'ERROR deleting {src}: {e}', file=sys.stderr)
            errors += 1

    # Append rmdir commands for created dirs, deepest first, so undo leaves no orphan dirs
    if created_dirs:
        undo_lines.append('')
        undo_lines.append('# Remove directories created by this sort (rmdir is a no-op if non-empty)')
        for d in sorted(created_dirs, key=lambda p: p.count(os.sep), reverse=True):
            undo_lines.append(f'rmdir {json.dumps(d)} 2>/dev/null || true')

    undo_path = os.path.join(root_folder, 'undo.sh')
    with open(undo_path, 'w') as f:
        f.write('\n'.join(undo_lines) + '\n')
    os.chmod(undo_path, 0o755)

    print(f'Done. Moved: {moved}, Deleted: {deleted}, Skipped: {len(skips)}, Errors: {errors}')
    print(f'Undo script written to: {undo_path}')

    if errors:
        sys.exit(1)


if __name__ == '__main__':
    main()
