#!/usr/bin/env python3
"""
Usage: python3 apply.py <plan.json> <root_folder> [--dry-run] [--to-mp3]

Applies a music sort plan, strips all metadata tags from every output file
via ffmpeg, optionally converts non-MP3 files to MP3 in the same ffmpeg pass,
and writes undo.sh to <root_folder>.

Requires ffmpeg: brew install ffmpeg

Plan format — a JSON array of objects, each with an "action" field:
  {"action": "MOVE",   "src": "/abs/src.mp3", "dst": "/abs/dst.mp3"}
  {"action": "DELETE", "src": "/abs/dup.mp3"}
  {"action": "SKIP",   "src": "/abs/file.mp3", "reason": "..."}

Exits non-zero on the first error. Prints a summary to stdout.
"""

import json
import os
import shutil
import subprocess
import sys


def check_ffmpeg():
    try:
        subprocess.run(['ffmpeg', '-version'], capture_output=True, check=True)
    except (FileNotFoundError, subprocess.CalledProcessError):
        print('ERROR: ffmpeg not found. Install with: brew install ffmpeg', file=sys.stderr)
        sys.exit(1)


def strip_tags(path):
    """Re-mux the file in place using ffmpeg, dropping all metadata."""
    base, ext = os.path.splitext(path)
    tmp = base + '.notags' + ext  # keep extension so ffmpeg auto-detects format
    try:
        result = subprocess.run(
            ['ffmpeg', '-i', path, '-map', '0:a', '-map_metadata', '-1',
             '-c:a', 'copy', tmp, '-y', '-loglevel', 'error'],
            capture_output=True,
        )
        if result.returncode != 0:
            raise RuntimeError(result.stderr.decode().strip())
        os.replace(tmp, path)
    except Exception as e:
        print(f'WARNING: could not strip tags from {path}: {e}', file=sys.stderr)
        if os.path.exists(tmp):
            os.remove(tmp)


def main():
    if len(sys.argv) < 3:
        print('Usage: apply.py <plan.json> <root_folder> [--dry-run] [--to-mp3]', file=sys.stderr)
        sys.exit(1)

    plan_path   = sys.argv[1]
    root_folder = os.path.expanduser(sys.argv[2])
    dry_run     = '--dry-run' in sys.argv
    to_mp3      = '--to-mp3' in sys.argv

    check_ffmpeg()

    with open(plan_path) as f:
        plan = json.load(f)

    moves   = [p for p in plan if p['action'] == 'MOVE']
    deletes = [p for p in plan if p['action'] == 'DELETE']
    skips   = [p for p in plan if p['action'] == 'SKIP']

    if dry_run:
        print(f'[dry-run] Would move {len(moves)} file(s), delete {len(deletes)}, skip {len(skips)}.')
        print(f'[dry-run] Tags would be stripped from all output files.')
        if to_mp3:
            non_mp3 = sum(1 for m in moves if os.path.splitext(m['src'])[1].lower() != '.mp3')
            print(f'[dry-run] {non_mp3} file(s) would be converted to MP3.')
        return

    undo_lines = [
        '#!/usr/bin/env bash',
        '# Undo script generated by music-sort',
        '# NOTE: tag stripping is irreversible. --to-mp3 conversions are also irreversible.',
        '',
    ]
    moved = deleted = errors = converted = 0
    created_dirs = set()

    for entry in moves:
        src, dst = entry['src'], entry['dst']
        try:
            if to_mp3:
                dst = os.path.splitext(dst)[0] + '.mp3'

            dst_dir = os.path.dirname(dst)
            parts = []
            d = dst_dir
            while not os.path.exists(d):
                parts.append(d)
                d = os.path.dirname(d)
            created_dirs.update(parts)
            os.makedirs(dst_dir, exist_ok=True)

            src_ext = os.path.splitext(src)[1].lower()
            if to_mp3 and src_ext != '.mp3':
                # Convert + strip tags in one ffmpeg pass
                result = subprocess.run(
                    ['ffmpeg', '-i', src, '-map', '0:a', '-map_metadata', '-1',
                     '-q:a', '0', dst, '-y', '-loglevel', 'error'],
                    capture_output=True,
                )
                if result.returncode != 0:
                    raise RuntimeError(result.stderr.decode().strip())
                os.remove(src)
                undo_lines.append(f'# CONVERTED (irreversible): {src} → {dst}')
                converted += 1
            else:
                shutil.move(src, dst)
                undo_lines.append(f'mv {json.dumps(dst)} {json.dumps(src)}')
                strip_tags(dst)

            moved += 1
        except Exception as e:
            print(f'ERROR processing {src} → {dst}: {e}', file=sys.stderr)
            errors += 1

    for entry in deletes:
        src = entry['src']
        try:
            undo_lines.append(f'# DELETED (cannot undo automatically): {src}')
            os.remove(src)
            deleted += 1
        except Exception as e:
            print(f'ERROR deleting {src}: {e}', file=sys.stderr)
            errors += 1

    # Append rmdir commands for created dirs, deepest first, so undo leaves no orphan dirs
    if created_dirs:
        undo_lines.append('')
        undo_lines.append('# Remove directories created by this sort (rmdir is a no-op if non-empty)')
        for d in sorted(created_dirs, key=lambda p: p.count(os.sep), reverse=True):
            undo_lines.append(f'rmdir {json.dumps(d)} 2>/dev/null || true')

    undo_path = os.path.join(root_folder, 'undo.sh')
    with open(undo_path, 'w') as f:
        f.write('\n'.join(undo_lines) + '\n')
    os.chmod(undo_path, 0o755)

    try:
        os.remove(plan_path)
    except OSError:
        pass

    extras = f', Converted to MP3: {converted}' if converted else ''
    print(f'Done. Moved: {moved}, Deleted: {deleted}, Skipped: {len(skips)}, Errors: {errors}{extras}')
    print('Tags stripped from all output files.')
    print(f'Undo script written to: {undo_path}')

    if errors:
        sys.exit(1)


if __name__ == '__main__':
    main()
